page17 = [
  {
    "Address": 0,
    "Hex": "0x00",
    "RA[5:0]": 0,
    "Name": "V1Sag_DUR",
    "Description": "V1 Sag Duration",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "int22",
    "Scale": "NULL"
  },
  {
    "Address": 1,
    "Hex": "0x01",
    "RA[5:0]": 1,
    "Name": "V1Sag_LEVEL",
    "Description": "V1 Sag Level",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float-23",
    "Scale": "NULL"
  },
  {
    "Address": 2,
    "Hex": "0x02",
    "RA[5:0]": 10,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 3,
    "Hex": "0x03",
    "RA[5:0]": 11,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 4,
    "Hex": "0x04",
    "RA[5:0]": 100,
    "Name": "I1Over_DUR",
    "Description": "I1 Overcurrent Duration",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "int22",
    "Scale": "NULL"
  },
  {
    "Address": 5,
    "Hex": "0x05",
    "RA[5:0]": 101,
    "Name": "I1Over_LEVEL",
    "Description": "I1 Overcurrent Level",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 7F FFFF",
    "Type": "float-23",
    "Scale": "NULL"
  },
  {
    "Address": 6,
    "Hex": "0x06",
    "RA[5:0]": 110,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 7,
    "Hex": "0x07",
    "RA[5:0]": 111,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 8,
    "Hex": "0x08",
    "RA[5:0]": 1000,
    "Name": "V2Sag_DUR",
    "Description": "V2 Sag Duration",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "int22",
    "Scale": "NULL"
  },
  {
    "Address": 9,
    "Hex": "0x09",
    "RA[5:0]": 1001,
    "Name": "V2Sag_LEVEL",
    "Description": "V2 Sag Level",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float-23",
    "Scale": "NULL"
  },
  {
    "Address": 10,
    "Hex": "0x0A",
    "RA[5:0]": 1010,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 11,
    "Hex": "0x0B",
    "RA[5:0]": 1011,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 12,
    "Hex": "0x0C",
    "RA[5:0]": 1100,
    "Name": "I2Over_DUR",
    "Description": "I2 Overcurrent Duration",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "int22",
    "Scale": "NULL"
  },
  {
    "Address": 13,
    "Hex": "0x0D",
    "RA[5:0]": 1101,
    "Name": "I2Over_LEVEL",
    "Description": "I2 Overcurrent Level",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 7F FFFF",
    "Type": "float-23",
    "Scale": "NULL"
  },
  {
    "Address": 14,
    "Hex": "0x0E",
    "RA[5:0]": 1110,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 15,
    "Hex": "0x0F",
    "RA[5:0]": 1111,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 16,
    "Hex": "0x10",
    "RA[5:0]": 10000,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 17,
    "Hex": "0x11",
    "RA[5:0]": 10001,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 18,
    "Hex": "0x12",
    "RA[5:0]": 10010,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 19,
    "Hex": "0x13",
    "RA[5:0]": 10011,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 20,
    "Hex": "0x14",
    "RA[5:0]": 10100,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 21,
    "Hex": "0x15",
    "RA[5:0]": 10101,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 22,
    "Hex": "0x16",
    "RA[5:0]": 10110,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 23,
    "Hex": "0x17",
    "RA[5:0]": 10111,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 24,
    "Hex": "0x18",
    "RA[5:0]": 11000,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 25,
    "Hex": "0x19",
    "RA[5:0]": 11001,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 26,
    "Hex": "0x1A",
    "RA[5:0]": 11010,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 27,
    "Hex": "0x1B",
    "RA[5:0]": 11011,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 28,
    "Hex": "0x1C",
    "RA[5:0]": 11100,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 29,
    "Hex": "0x1D",
    "RA[5:0]": 11101,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 30,
    "Hex": "0x1E",
    "RA[5:0]": 11110,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 31,
    "Hex": "0x1F",
    "RA[5:0]": 11111,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  }
]