page0 = [
  {
    "Address": 0,
    "Hex": "0x00",
    "RA[5:0]": 0,
    "Name": "Config0",
    "Description": "Configuration 0",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x C0 2000",
    "Type": "conf",
    "Scale": "NULL"
  },
  {
    "Address": 1,
    "Hex": "0x01",
    "RA[5:0]": 1,
    "Name": "Config1",
    "Description": "Configuration 1",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 00 EEEE",
    "Type": "conf",
    "Scale": "NULL"
  },
  {
    "Address": 2,
    "Hex": "0x02",
    "RA[5:0]": 10,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 3,
    "Hex": "0x03",
    "RA[5:0]": 11,
    "Name": "Mask",
    "Description": "Interrupt Mask",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "conf",
    "Scale": "NULL"
  },
  {
    "Address": 4,
    "Hex": "0x04",
    "RA[5:0]": 100,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 5,
    "Hex": "0x05",
    "RA[5:0]": 101,
    "Name": "PC",
    "Description": "Phase Compensation Control",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "conf",
    "Scale": "NULL"
  },
  {
    "Address": 6,
    "Hex": "0x06",
    "RA[5:0]": 110,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 7,
    "Hex": "0x07",
    "RA[5:0]": 111,
    "Name": "SerialCtrl",
    "Description": "UART Control",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 02 004D",
    "Type": "conf",
    "Scale": "NULL"
  },
  {
    "Address": 8,
    "Hex": "0x08",
    "RA[5:0]": 1000,
    "Name": "PulseWidth",
    "Description": "Energy Pulse Width",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 00 0001",
    "Type": "conf",
    "Scale": "NULL"
  },
  {
    "Address": 9,
    "Hex": "0x09",
    "RA[5:0]": 1001,
    "Name": "PulseCtrl",
    "Description": "Energy Pulse Control",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "conf",
    "Scale": "NULL"
  },
  {
    "Address": 10,
    "Hex": "0x0A",
    "RA[5:0]": 1010,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 11,
    "Hex": "0x0B",
    "RA[5:0]": 1011,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 12,
    "Hex": "0x0C",
    "RA[5:0]": 1100,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 13,
    "Hex": "0x0D",
    "RA[5:0]": 1101,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 14,
    "Hex": "0x0E",
    "RA[5:0]": 1110,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 15,
    "Hex": "0x0F",
    "RA[5:0]": 1111,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 16,
    "Hex": "0x10",
    "RA[5:0]": 10000,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 17,
    "Hex": "0x11",
    "RA[5:0]": 10001,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 18,
    "Hex": "0x12",
    "RA[5:0]": 10010,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 19,
    "Hex": "0x13",
    "RA[5:0]": 10011,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 20,
    "Hex": "0x14",
    "RA[5:0]": 10100,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 21,
    "Hex": "0x15",
    "RA[5:0]": 10101,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 22,
    "Hex": "0x16",
    "RA[5:0]": 10110,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 23,
    "Hex": "0x17",
    "RA[5:0]": 10111,
    "Name": "Status0",
    "Description": "Interrupt Status",
    "Protect": "",
    "DSP": "N",
    "HOST": "N",
    "Default": "0x 80 0000",
    "Type": "conf",
    "Scale": "NULL"
  },
  {
    "Address": 24,
    "Hex": "0x18",
    "RA[5:0]": 11000,
    "Name": "Status1",
    "Description": "Chip Status 1",
    "Protect": "",
    "DSP": "N",
    "HOST": "N",
    "Default": "0x 80 1800",
    "Type": "conf",
    "Scale": "NULL"
  },
  {
    "Address": 25,
    "Hex": "0x19",
    "RA[5:0]": 11001,
    "Name": "Status2",
    "Description": "Chip Status 2",
    "Protect": "",
    "DSP": "N",
    "HOST": "N",
    "Default": "0x 00 0000",
    "Type": "conf",
    "Scale": "NULL"
  },
  {
    "Address": 26,
    "Hex": "0x1A",
    "RA[5:0]": 11010,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 27,
    "Hex": "0x1B",
    "RA[5:0]": 11011,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 28,
    "Hex": "0x1C",
    "RA[5:0]": 11100,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 29,
    "Hex": "0x1D",
    "RA[5:0]": 11101,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 30,
    "Hex": "0x1E",
    "RA[5:0]": 11110,
    "Name": "ONCHIP_RS",
    "Description": "Reserved Erratum 2",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "0x 0C 0008",
    "Type": "conf",
    "Scale": "NULL"
  },
  {
    "Address": 31,
    "Hex": "0x1F",
    "RA[5:0]": 11111,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 32,
    "Hex": "0x20",
    "RA[5:0]": 100000,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 33,
    "Hex": "0x21",
    "RA[5:0]": 100001,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 34,
    "Hex": "0x22",
    "RA[5:0]": 100010,
    "Name": "RegLock",
    "Description": "Register Lock Control",
    "Protect": "*",
    "DSP": "N",
    "HOST": "N",
    "Default": "0x 00 0000",
    "Type": "conf",
    "Scale": "NULL"
  },
  {
    "Address": 35,
    "Hex": "0x23",
    "RA[5:0]": 100011,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 36,
    "Hex": "0x24",
    "RA[5:0]": 100100,
    "Name": "V1_PEAK",
    "Description": "V1 Peak Voltage",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float-23",
    "Scale": "V1_SCALE"
  },
  {
    "Address": 37,
    "Hex": "0x25",
    "RA[5:0]": 100101,
    "Name": "I1_PEAK",
    "Description": "I1 Peak Current",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float-23",
    "Scale": "I1_SCALE"
  },
  {
    "Address": 38,
    "Hex": "0x26",
    "RA[5:0]": 100110,
    "Name": "V2_PEAK",
    "Description": "V2 Peak Voltage",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float-23",
    "Scale": "V2_SCALE"
  },
  {
    "Address": 39,
    "Hex": "0x27",
    "RA[5:0]": 100111,
    "Name": "I2_PEAK",
    "Description": "I2 Peak Current",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float-23",
    "Scale": "I2_SCALE"
  },
  {
    "Address": 40,
    "Hex": "0x28",
    "RA[5:0]": 101000,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 41,
    "Hex": "0x29",
    "RA[5:0]": 101001,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 42,
    "Hex": "0x2A",
    "RA[5:0]": 101010,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 43,
    "Hex": "0x2B",
    "RA[5:0]": 101011,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 44,
    "Hex": "0x2C",
    "RA[5:0]": 101100,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 45,
    "Hex": "0x2D",
    "RA[5:0]": 101101,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 46,
    "Hex": "0x2E",
    "RA[5:0]": 101110,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 47,
    "Hex": "0x2F",
    "RA[5:0]": 101111,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 48,
    "Hex": "0x30",
    "RA[5:0]": 110000,
    "Name": "PSDC",
    "Description": "Phase Sequence Detection & Control",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "conf",
    "Scale": "NULL"
  },
  {
    "Address": 49,
    "Hex": "0x31",
    "RA[5:0]": 110001,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 50,
    "Hex": "0x32",
    "RA[5:0]": 110010,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 51,
    "Hex": "0x33",
    "RA[5:0]": 110011,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 52,
    "Hex": "0x34",
    "RA[5:0]": 110100,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 53,
    "Hex": "0x35",
    "RA[5:0]": 110101,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 54,
    "Hex": "0x36",
    "RA[5:0]": 110110,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 55,
    "Hex": "0x37",
    "RA[5:0]": 110111,
    "Name": "ZX_NUM",
    "Description": "Num. Zero Crosses used for Line Freq.",
    "Protect": "",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 00 0064",
    "Type": "int23",
    "Scale": "NULL"
  },
  {
    "Address": 56,
    "Hex": "0x38",
    "RA[5:0]": 111000,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 57,
    "Hex": "0x39",
    "RA[5:0]": 111001,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 58,
    "Hex": "0x3A",
    "RA[5:0]": 111010,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 59,
    "Hex": "0x3B",
    "RA[5:0]": 111011,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 60,
    "Hex": "0x3C",
    "RA[5:0]": 111100,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 61,
    "Hex": "0x3D",
    "RA[5:0]": 111101,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 62,
    "Hex": "0x3E",
    "RA[5:0]": 111110,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 63,
    "Hex": "0x3F",
    "RA[5:0]": 111111,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  }
]