page18 = [
  {
    "Address": 24,
    "Hex": "0x18",
    "RA[5:0]": 11000,
    "Name": "IZX_LEVEL",
    "Description": "I-channel Zero-crossing Threshold",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 10 0000",
    "Type": "float-23",
    "Scale": "NULL"
  },
  {
    "Address": 25,
    "Hex": "0x19",
    "RA[5:0]": 11001,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 26,
    "Hex": "0x1A",
    "RA[5:0]": 11010,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 27,
    "Hex": "0x1B",
    "RA[5:0]": 11011,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 28,
    "Hex": "0x1C",
    "RA[5:0]": 11100,
    "Name": "PULSERATE",
    "Description": "Energy Pulse Rate",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 80 0000",
    "Type": "float-23",
    "Scale": "NULL"
  },
  {
    "Address": 29,
    "Hex": "0x1D",
    "RA[5:0]": 11101,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 30,
    "Hex": "0x1E",
    "RA[5:0]": 11110,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 31,
    "Hex": "0x1F",
    "RA[5:0]": 11111,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 32,
    "Hex": "0x20",
    "RA[5:0]": 100000,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 33,
    "Hex": "0x21",
    "RA[5:0]": 100001,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 34,
    "Hex": "0x22",
    "RA[5:0]": 100010,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 35,
    "Hex": "0x23",
    "RA[5:0]": 100011,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 36,
    "Hex": "0x24",
    "RA[5:0]": 100100,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 37,
    "Hex": "0x25",
    "RA[5:0]": 100101,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 38,
    "Hex": "0x26",
    "RA[5:0]": 100110,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 39,
    "Hex": "0x27",
    "RA[5:0]": 100111,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 40,
    "Hex": "0x28",
    "RA[5:0]": 101000,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 41,
    "Hex": "0x29",
    "RA[5:0]": 101001,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 42,
    "Hex": "0x2A",
    "RA[5:0]": 101010,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 43,
    "Hex": "0x2B",
    "RA[5:0]": 101011,
    "Name": "ROGOWSKI_GAIN",
    "Description": "Rogowski Coil lntegrator Gain",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 14 3958",
    "Type": "float-23",
    "Scale": "NULL"
  },
  {
    "Address": 44,
    "Hex": "0x2C",
    "RA[5:0]": 101100,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 45,
    "Hex": "0x2D",
    "RA[5:0]": 101101,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 46,
    "Hex": "0x2E",
    "RA[5:0]": 101110,
    "Name": "V_SWELL_DUR",
    "Description": "V Swell Duration",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "int22",
    "Scale": "NULL"
  },
  {
    "Address": 47,
    "Hex": "0x2F",
    "RA[5:0]": 101111,
    "Name": "V_SWELL_LEVEL",
    "Description": "V Swell Level",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 7F FFFF",
    "Type": "float-23",
    "Scale": "NULL"
  },
  {
    "Address": 48,
    "Hex": "0x30",
    "RA[5:0]": 110000,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 49,
    "Hex": "0x31",
    "RA[5:0]": 110001,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 50,
    "Hex": "0x32",
    "RA[5:0]": 110010,
    "Name": "",
    "Description": "Reserved",
    "Protect": "*",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 51,
    "Hex": "0x33",
    "RA[5:0]": 110011,
    "Name": "",
    "Description": "Reserved",
    "Protect": "*",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 52,
    "Hex": "0x34",
    "RA[5:0]": 110100,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 53,
    "Hex": "0x35",
    "RA[5:0]": 110101,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 54,
    "Hex": "0x36",
    "RA[5:0]": 110110,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 55,
    "Hex": "0x37",
    "RA[5:0]": 110111,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 56,
    "Hex": "0x38",
    "RA[5:0]": 111000,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 57,
    "Hex": "0x39",
    "RA[5:0]": 111001,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 58,
    "Hex": "0x3A",
    "RA[5:0]": 111010,
    "Name": "V_ZX_LEVEL",
    "Description": "V-channel Zero-crossing Threshold",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 10 0000",
    "Type": "float-23",
    "Scale": "NULL"
  },
  {
    "Address": 59,
    "Hex": "0x3B",
    "RA[5:0]": 111011,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 60,
    "Hex": "0x3C",
    "RA[5:0]": 111100,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 61,
    "Hex": "0x3D",
    "RA[5:0]": 111101,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 62,
    "Hex": "0x3E",
    "RA[5:0]": 111110,
    "Name": "CYCLECOUNT",
    "Description": "Line Cycle Count",
    "Protect": "**",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0064",
    "Type": "int22",
    "Scale": "NULL"
  },
  {
    "Address": 63,
    "Hex": "0x3F",
    "RA[5:0]": 111111,
    "Name": "SCALE_IGAIN",
    "Description": "Scale Value for I-channel Gain Calibration",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 4C CCCC",
    "Type": "float-23",
    "Scale": "NULL"
  }
]