page16 = [
  {
    "Address": 0,
    "Hex": "0x00",
    "RA[5:0]": 0,
    "Name": "CONFIG2",
    "Description": "Configuration 2",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 10 0200",
    "Type": "conf",
    "Scale": "NULL"
  },
  {
    "Address": 1,
    "Hex": "0x01",
    "RA[5:0]": 1,
    "Name": "REGCHK",
    "Description": "Register Checksum",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "int23",
    "Scale": "NULL"
  },
  {
    "Address": 2,
    "Hex": "0x02",
    "RA[5:0]": 10,
    "Name": "I_INST",
    "Description": "I Instantaneous Current",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float-23",
    "Scale": "I1_SCALE"
  },
  {
    "Address": 3,
    "Hex": "0x03",
    "RA[5:0]": 11,
    "Name": "V_INST",
    "Description": "V Instantaneous Voltage",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float-23",
    "Scale": "V1_SCALE"
  },
  {
    "Address": 4,
    "Hex": "0x04",
    "RA[5:0]": 100,
    "Name": "P_INST",
    "Description": "Instantaneous Power",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float-23",
    "Scale": "P1_SCALE"
  },
  {
    "Address": 5,
    "Hex": "0x05",
    "RA[5:0]": 101,
    "Name": "P_ACTIVE",
    "Description": "Active Power",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float-23",
    "Scale": "P1_SCALE"
  },
  {
    "Address": 6,
    "Hex": "0x06",
    "RA[5:0]": 110,
    "Name": "I_RMS",
    "Description": "I RMS Current",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float24",
    "Scale": "I1_SCALE"
  },
  {
    "Address": 7,
    "Hex": "0x07",
    "RA[5:0]": 111,
    "Name": "V_RMS",
    "Description": "V RMS Voltage",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float24",
    "Scale": "V1_SCALE"
  },
  {
    "Address": 8,
    "Hex": "0x08",
    "RA[5:0]": 1000,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 9,
    "Hex": "0x09",
    "RA[5:0]": 1001,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 10,
    "Hex": "0x0A",
    "RA[5:0]": 1010,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 11,
    "Hex": "0x0B",
    "RA[5:0]": 1011,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 12,
    "Hex": "0x0C",
    "RA[5:0]": 1100,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 13,
    "Hex": "0x0D",
    "RA[5:0]": 1101,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 14,
    "Hex": "0x0E",
    "RA[5:0]": 1110,
    "Name": "P_REACTIVE",
    "Description": "Reactive Power",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float-23",
    "Scale": "P1_SCALE"
  },
  {
    "Address": 15,
    "Hex": "0x0F",
    "RA[5:0]": 1111,
    "Name": "P_REACTIVE_INST",
    "Description": "Instantaneous Reactive Power",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float-23",
    "Scale": "P1_SCALE"
  },
  {
    "Address": 16,
    "Hex": "0x10",
    "RA[5:0]": 10000,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 17,
    "Hex": "0x11",
    "RA[5:0]": 10001,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 18,
    "Hex": "0x12",
    "RA[5:0]": 10010,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 19,
    "Hex": "0x13",
    "RA[5:0]": 10011,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 20,
    "Hex": "0x14",
    "RA[5:0]": 10100,
    "Name": "P_APPARENT",
    "Description": "Apparent Power",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float23",
    "Scale": "P1_SCALE"
  },
  {
    "Address": 21,
    "Hex": "0x15",
    "RA[5:0]": 10101,
    "Name": "PF_FACTOR",
    "Description": "Power Factor",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float-23",
    "Scale": "NULL"
  },
  {
    "Address": 22,
    "Hex": "0x16",
    "RA[5:0]": 10110,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 23,
    "Hex": "0x17",
    "RA[5:0]": 10111,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 24,
    "Hex": "0x18",
    "RA[5:0]": 11000,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 25,
    "Hex": "0x19",
    "RA[5:0]": 11001,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 26,
    "Hex": "0x1A",
    "RA[5:0]": 11010,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 27,
    "Hex": "0x1B",
    "RA[5:0]": 11011,
    "Name": "TEMPERATURE",
    "Description": "Temperature",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float-16",
    "Scale": "NULL"
  },
  {
    "Address": 28,
    "Hex": "0x1C",
    "RA[5:0]": 11100,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 29,
    "Hex": "0x1D",
    "RA[5:0]": 11101,
    "Name": "P_ACTIVE_SUM",
    "Description": "Total Active Power",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float-23",
    "Scale": "P1_SCALE"
  },
  {
    "Address": 30,
    "Hex": "0x1E",
    "RA[5:0]": 11110,
    "Name": "P_APPARENT_SUM",
    "Description": "Total Apparent Power",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float23",
    "Scale": "P1_SCALE"
  },
  {
    "Address": 31,
    "Hex": "0x1F",
    "RA[5:0]": 11111,
    "Name": "P_REACTIVE_SUM",
    "Description": "Total Reactive Power",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float-23",
    "Scale": "P1_SCALE"
  },
  {
    "Address": 32,
    "Hex": "0x20",
    "RA[5:0]": 100000,
    "Name": "I_DC_OFFSET",
    "Description": "I DC Offset",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float-23",
    "Scale": "NULL"
  },
  {
    "Address": 33,
    "Hex": "0x21",
    "RA[5:0]": 100001,
    "Name": "I_GAIN",
    "Description": "I Gain",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 40 0000",
    "Type": "float22",
    "Scale": "NULL"
  },
  {
    "Address": 34,
    "Hex": "0x22",
    "RA[5:0]": 100010,
    "Name": "V_DC_OFFSET",
    "Description": "V DC Offset",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float23",
    "Scale": "NULL"
  },
  {
    "Address": 35,
    "Hex": "0x23",
    "RA[5:0]": 100011,
    "Name": "V_GAIN",
    "Description": "V Gain",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 40 0000",
    "Type": "float22",
    "Scale": "NULL"
  },
  {
    "Address": 36,
    "Hex": "0x24",
    "RA[5:0]": 100100,
    "Name": "P_OFFSET",
    "Description": "Average Active Power Offset",
    "Protect": "*",
    "DSP": "",
    "HOST": "",
    "Default": "0x 00 0000",
    "Type": "float-23",
    "Scale": "NULL"
  },
  {
    "Address": 37,
    "Hex": "0x25",
    "RA[5:0]": 100101,
    "Name": "I_AC_OFFSET",
    "Description": "I AC Offset",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float24",
    "Scale": "NULL"
  },
  {
    "Address": 38,
    "Hex": "0x26",
    "RA[5:0]": 100110,
    "Name": "Q_OFFSET",
    "Description": "Average Reactive Power Offset",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float-23",
    "Scale": "NULL"
  },
  {
    "Address": 39,
    "Hex": "0x27",
    "RA[5:0]": 100111,
    "Name": "",
    "Description": "Reserved",
    "Protect": "*",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 40,
    "Hex": "0x28",
    "RA[5:0]": 101000,
    "Name": "",
    "Description": "Reserved",
    "Protect": "*",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 41,
    "Hex": "0x29",
    "RA[5:0]": 101001,
    "Name": "",
    "Description": "Reserved",
    "Protect": "*",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 42,
    "Hex": "0x2A",
    "RA[5:0]": 101010,
    "Name": "",
    "Description": "Reserved",
    "Protect": "*",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 43,
    "Hex": "0x2B",
    "RA[5:0]": 101011,
    "Name": "",
    "Description": "Reserved",
    "Protect": "*",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 44,
    "Hex": "0x2C",
    "RA[5:0]": 101100,
    "Name": "",
    "Description": "Reserved",
    "Protect": "*",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 45,
    "Hex": "0x2D",
    "RA[5:0]": 101101,
    "Name": "",
    "Description": "Reserved",
    "Protect": "*",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 46,
    "Hex": "0x2E",
    "RA[5:0]": 101110,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 47,
    "Hex": "0x2F",
    "RA[5:0]": 101111,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 48,
    "Hex": "0x30",
    "RA[5:0]": 110000,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 49,
    "Hex": "0x31",
    "RA[5:0]": 110001,
    "Name": "EPSILON",
    "Description": "Ratio of Line to Sample Frequency",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 01 999A",
    "Type": "float-23",
    "Scale": "FREQ_SCALE"
  },
  {
    "Address": 50,
    "Hex": "0x32",
    "RA[5:0]": 110010,
    "Name": "",
    "Description": "Reserved",
    "Protect": "*",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 51,
    "Hex": "0x33",
    "RA[5:0]": 110011,
    "Name": "SAMPLECOUNT",
    "Description": "Sample Count",
    "Protect": "**",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0FA0",
    "Type": "int22",
    "Scale": "NULL"
  },
  {
    "Address": 52,
    "Hex": "0x34",
    "RA[5:0]": 110100,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 53,
    "Hex": "0x35",
    "RA[5:0]": 110101,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 54,
    "Hex": "0x36",
    "RA[5:0]": 110110,
    "Name": "TEMP_GAIN",
    "Description": "Temperature Gain",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 06 B716",
    "Type": "float16",
    "Scale": "NULL"
  },
  {
    "Address": 55,
    "Hex": "0x37",
    "RA[5:0]": 110111,
    "Name": "TEMP_OFFSET",
    "Description": "Temperature Offset",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x D5 3998",
    "Type": "float-16",
    "Scale": "NULL"
  },
  {
    "Address": 56,
    "Hex": "0x38",
    "RA[5:0]": 111000,
    "Name": "",
    "Description": "Reserved",
    "Protect": "*",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 57,
    "Hex": "0x39",
    "RA[5:0]": 111001,
    "Name": "TIME_SETTLE",
    "Description": "Filter Settling Time to Conv. Startup",
    "Protect": "",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 00 001E",
    "Type": "int23",
    "Scale": "NULL"
  },
  {
    "Address": 58,
    "Hex": "0x3A",
    "RA[5:0]": 111010,
    "Name": "LOAD_MIN",
    "Description": "No Load Threshold",
    "Protect": "*",
    "DSP": "Y",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "float-23",
    "Scale": "NULL"
  },
  {
    "Address": 59,
    "Hex": "0x3B",
    "RA[5:0]": 111011,
    "Name": "",
    "Description": "Reserved",
    "Protect": "*",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 60,
    "Hex": "0x3C",
    "RA[5:0]": 111100,
    "Name": "SYS_GAIN",
    "Description": "System Gain",
    "Protect": "*",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 50 0000",
    "Type": "float-22",
    "Scale": "NULL"
  },
  {
    "Address": 61,
    "Hex": "0x3D",
    "RA[5:0]": 111101,
    "Name": "TIME_SYS",
    "Description": "System Time (in samples)",
    "Protect": "",
    "DSP": "N",
    "HOST": "Y",
    "Default": "0x 00 0000",
    "Type": "int23",
    "Scale": "NULL"
  },
  {
    "Address": 62,
    "Hex": "0x3E",
    "RA[5:0]": 111110,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  },
  {
    "Address": 63,
    "Hex": "0x3F",
    "RA[5:0]": 111111,
    "Name": "",
    "Description": "Reserved",
    "Protect": "",
    "DSP": "",
    "HOST": "",
    "Default": "",
    "Type": "",
    "Scale": ""
  }
]